name: Docker Image CI - QA Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'microservices/qa/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'microservices/qa/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.ACCESS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image for QA service
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/qa-service
        TAG=$(date +%s)

        # Build the image using the correct path to Dockerfile
        docker build -t $IMAGE_NAME:$TAG -f microservices/qa/Dockerfile .

        # Push the image
        docker push $IMAGE_NAME:$TAG
